chore(dependencies): Upgrade Spring Boot to 2.3.12
Upgraded following dependencies along with spring boot to 2.3.12.RELEASE:

groovy-all:2.5.14
jooq:3.13.6

Cleaned up following dependencies and constraints as being part of spring boot 2.3.12.RELEASE:

spring-framework-bom
assertj-core
postgresql

While building kork with upgrade, faced errors like:

Task :kork-core:compileJava
/kork/kork-core/src/main/java/com/netflix/spinnaker/kork/lock/LockManager.java:19: error: package com.fasterxml.jackson.annotation does not exist
import com.fasterxml.jackson.annotation.JsonCreator;
                                       ^
/kork/kork-core/src/main/java/com/netflix/spinnaker/kork/lock/LockManager.java:20: error: package com.fasterxml.jackson.annotation does not exist
import com.fasterxml.jackson.annotation.JsonInclude;
                                       ^
/kork/kork-core/src/main/java/com/netflix/spinnaker/kork/lock/LockManager.java:21: error: package com.fasterxml.jackson.annotation does not exist
import com.fasterxml.jackson.annotation.JsonProperty;
                                       ^
To resolve errors, introduced explicit implementation of com.fasterxml.jackson.core:jackson-annotations and com.fasterxml.jackson.core:jackson-databind in kork-core.gradle.

And com.fasterxml.jackson.core:jackson-databind in kork-jedis.gradle